name: Matrix Demo Workflow
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  matrix_demo:
    continue-on-error: true
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 16, 18, 20, 21]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install Node.js of version ${{ matrix.node-version }} and npm
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependiencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Show Node.js and npm Versions and Operating System 
        run: |
          node -v
          npm -v
          echo "Operating System: ${{ matrix.operating-system }}"
